style: is-light
height: is-medium
items:
  - title: General Consultation
    icon: fa-stethoscope
    description: >
      Klinik Merdeka is the primary point of contact for patients
      seeking general healthcare services. 

 